" Plug
" https://github.com/junegunn/vim-plug
call plug#begin('~/.config/nvim/plugged')

Plug 'gmarik/Vundle.vim'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'mileszs/ack.vim'
Plug 'rking/ag.vim'
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'ntpeters/vim-better-whitespace'
Plug 'airblade/vim-gitgutter'
Plug 'easymotion/vim-easymotion'
Plug 'jeetsukumaran/vim-buffergator'
Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'tomtom/tlib_vim'
Plug 'garbas/vim-snipmate'
Plug 'honza/vim-snippets'
Plug 'tpope/vim-rails'
Plug 'itchyny/lightline.vim'
Plug 'wting/rust.vim'
Plug 'Raimondi/delimitMate'
Plug 'digitaltoad/vim-jade'
Plug 'vim-scripts/nginx.vim'
Plug 'ekalinin/Dockerfile.vim'
Plug 'editorconfig/editorconfig-vim'
Plug 'Yggdroot/indentLine'
Plug 'benekastah/neomake'
Plug 'majutsushi/tagbar'
Plug 'Valloric/YouCompleteMe'
Plug 'floobits/floobits-neovim'
Plug 'morhetz/gruvbox'
Plug 'fatih/vim-go'

" Themes
Plug 'joshdick/onedark.vim'
Plug 'matthewtodd/vim-twilight'
Plug 'Lokaltog/vim-distinguished'
Plug 'sjl/badwolf'

call plug#end()

"The comma leader
let mapleader=","

filetype plugin indent on
syntax on
au BufNewFile,BufRead *.sls setlocal ft=yaml
" colorscheme distinguished
colorscheme badwolf
" Better whitespace color highlight. Less annoying
highlight ExtraWhitespace ctermbg=lightgreen

set hlsearch
set expandtab
set tabstop=2 shiftwidth=2 softtabstop=2
set showcmd
set number
set backspace=2

" Flymode
let g:AutoPairsFlyMode = 1

" Turn off tab for completion
let g:ycm_key_list_select_completion = ['<Enter>', '<Down>']

" Undo
set undodir=~/.nvim/undodir
set undofile
set undolevels=1000
set undoreload=10000

" Key maps
inoremap jk <ESC>
nnoremap K i<CR><Esc>
noremap <leader>cs :let @/=''<cr>`
map <C-n> :NERDTreeToggle<CR>


" Buffergator
let g:buffergator_viewport_split_policy="T"

" Some mouse settings
set ttyfast
set mouse=a

let g:indentLine_char = '¦'
let g:indent_guides_enable_on_vim_startup=1
let g:indentLine_enabled = 1
let g:indent_guides_auto_colors = 1
let g:indentLine_leadingSpaceEnabled = 0
let g:indentLine_leadingSpaceChar = '·'

" NERDTree config
let NERDTreeIgnore = ['\.pyc$', '\.pyo$']
let NERDTreeShowHidden=0

" Some kay maps
nnoremap <CR> o<Esc>
nnoremap <leader>j i<CR><Esc>==

" Faster ctrlp using VCS
let g:ctrlp_user_command = {
	\ 'types': {
		\ 1: ['.git', 'cd %s && git ls-files'],
		\ 2: ['.hg', 'hg --cwd %s locate -I .'],
		\ },
	\ 'fallback': 'find %s -type f'
	\ }

"" Neomake
" run make on each save
autocmd! BufWritePost * Neomake
