" Plug
" https://github.com/junegunn/vim-plug
call plug#begin('~/.config/nvim/plugged')

Plug 'gmarik/Vundle.vim'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'mileszs/ack.vim'
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'ntpeters/vim-better-whitespace'
Plug 'airblade/vim-gitgutter'
Plug 'Lokaltog/vim-easymotion'
Plug 'jeetsukumaran/vim-buffergator'
Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'tomtom/tlib_vim'
Plug 'garbas/vim-snipmate'
Plug 'honza/vim-snippets'
Plug 'tpope/vim-rails'
Plug 'itchyny/lightline.vim'
Plug 'wting/rust.vim'
Plug 'Townk/vim-autoclose'
Plug 'digitaltoad/vim-jade'
Plug 'vim-scripts/nginx.vim'
Plug 'ekalinin/Dockerfile.vim'
Plug 'editorconfig/editorconfig-vim'
Plug 'Yggdroot/indentLine'
Plug 'benekastah/neomake'
Plug 'mileszs/ack.vim'
Plug 'majutsushi/tagbar'

" Themes
Plug 'tomasr/molokai'
Plug 'vim-scripts/xoria256.vim'
Plug 'joshdick/onedark.vim'

call plug#end()

"The comma leader
let mapleader=","

filetype plugin indent on
syntax on
colorscheme onedark
" Better whitespace color highlight. Less annoying
highlight ExtraWhitespace ctermbg=lightgreen

set hlsearch
set expandtab
set tabstop=2 shiftwidth=2 softtabstop=2
set showcmd
set number
set backspace=2

" Flymode
let g:AutoPairsFlyMode = 1

" Undo
set undodir=~/.nvim/undodir
set undofile
set undolevels=1000
set undoreload=10000

" Better escape key
inoremap jk <ESC>

" Buffergator
let g:buffergator_viewport_split_policy="T"

" Some mouse settings
set ttyfast
set mouse=a

let g:indentLine_char = '¦'
let g:indent_guides_enable_on_vim_startup=1
let g:indentLine_enabled = 0
let g:indent_guides_auto_colors = 0
let g:indentLine_leadingSpaceEnabled = 0
let g:indentLine_leadingSpaceChar = '·'

" NERDTree config
let NERDTreeIgnore = ['\.pyc$', '\.pyo$']
let NERDTreeShowHidden=1
